
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.resanet.ws.commentaire;

import java.util.ArrayList;
import java.util.List;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-24T15:00:00.813+02:00
 * Generated source version: 3.1.2
 * 
 */

@WebService(
                      serviceName = "commentaireService",
                      portName = "commentaireServicePort",
                      targetNamespace = "http://www.resanet.partenaires.com/commentaire",
                      endpointInterface = "com.resanet.ws.commentaire.CommentairePortType")
                      
public class CommentaireServicePortImpl implements CommentairePortType {

//    private static final Logger LOG = Logger.getLogger(CommentaireServicePortImpl.class.getName());

    
	private static List<Ajouter> listHotel = new ArrayList<Ajouter>();
	
	public CommentaireServicePortImpl(){
		
	}
	
    /* (non-Javadoc)
     * @see com.resanet.ws.commentaire.CommentairePortType#lister(java.lang.String  hotel )*
     */
    public java.util.List<java.lang.String> lister(java.lang.String hotel) throws ListerFault    { 
//        LOG.info("Executing operation lister");
        System.out.println(hotel);
        try {
			java.util.List<java.lang.String> _return = new ArrayList<String>();

			for (Ajouter item : listHotel) {
				if (item.getHotel().equals(hotel))
					_return.add(item.getCommentaire());
			}

            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ListerFault("listerFault...");
    }

    /* (non-Javadoc)
     * @see com.resanet.ws.commentaire.CommentairePortType#ajouter(java.lang.String  hotel ,)java.lang.String  commentaire )*
     */
    public void ajouter(java.lang.String hotel,java.lang.String commentaire) { 
//        LOG.info("Executing operation ajouter");
        System.out.println(hotel);
        System.out.println(commentaire);
        
        Ajouter parametreAjouter = new Ajouter();
        parametreAjouter.setCommentaire(commentaire);
        parametreAjouter.setHotel(hotel);
        
        try {
			listHotel.add(parametreAjouter);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
