
package com.resanet.ws.commentaire;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-24T14:58:07.441+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "commentaireFault", targetNamespace = "http://www.resanet.partenaires.com/commentaire")
public class ListerFault extends Exception {
    
    private com.resanet.ws.commentaire.CommentaireFault commentaireFault;

    public ListerFault() {
        super();
    }
    
    public ListerFault(String message) {
        super(message);
    }
    
    public ListerFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ListerFault(String message, com.resanet.ws.commentaire.CommentaireFault commentaireFault) {
        super(message);
        this.commentaireFault = commentaireFault;
    }

    public ListerFault(String message, com.resanet.ws.commentaire.CommentaireFault commentaireFault, Throwable cause) {
        super(message, cause);
        this.commentaireFault = commentaireFault;
    }

    public com.resanet.ws.commentaire.CommentaireFault getFaultInfo() {
        return this.commentaireFault;
    }
}
