package com.resanet.ws.commentaire;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-11-06T00:52:54.575+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.resanet.partenaires.com/commentaire", name = "commentairePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CommentairePortType {

    @WebResult(name = "commentaire", targetNamespace = "http://www.resanet.partenaires.com/commentaire")
    @RequestWrapper(localName = "lister", targetNamespace = "http://www.resanet.partenaires.com/commentaire", className = "com.resanet.ws.commentaire.Lister")
    @WebMethod
    @ResponseWrapper(localName = "listerResponse", targetNamespace = "http://www.resanet.partenaires.com/commentaire", className = "com.resanet.ws.commentaire.ListerResponse")
    public java.util.List<java.lang.String> lister(
        @WebParam(name = "hotel", targetNamespace = "http://www.resanet.partenaires.com/commentaire")
        java.lang.String hotel
    ) throws ListerFault;

    @Oneway
    @RequestWrapper(localName = "ajouter", targetNamespace = "http://www.resanet.partenaires.com/commentaire", className = "com.resanet.ws.commentaire.Ajouter")
    @WebMethod
    public void ajouter(
        @WebParam(name = "hotel", targetNamespace = "http://www.resanet.partenaires.com/commentaire")
        java.lang.String hotel,
        @WebParam(name = "commentaire", targetNamespace = "http://www.resanet.partenaires.com/commentaire")
        java.lang.String commentaire
    );
}
